### ISSUE TITLE
CloseEvent throws NoClassDefFoundError [ForgeGradle]

### ISSUE THREAD

**Issue by AnonymousHacker1279** [i-am-cal/antisteal#4]
When trying to use the mod during development in Forge (37.0.33), this error is thrown:
``java.lang.NoClassDefFoundError: i/am/cal/antisteal/Antisteal$CloseEvent``, which is caused by ``java.lang.ClassNotFoundException: i.am.cal.antisteal.Antisteal$CloseEvent``.

This is what I'm using to run the check method:
```java
try {
	CodeSource codeSource = MyClass.class.getProtectionDomain().getCodeSource();
	File jarFile = new File(codeSource.getLocation().toURI().getPath());
	String jarDir = jarFile.getParentFile().getPath();
	path = Paths.get(jarDir);
	HashMap<String, String> map = new HashMap<>(1);
	map.put("Curseforge", "curseforge.com/minecraft/mc-mods/my-mod");
	Antisteal.check(path, () -> Minecraft.getInstance().close(), map, MyClass.class);
} catch (URISyntaxException exception) {
	LOGGER.error(exception);
}
```

In my ``build.gradle``, I have ``implementation fg.deobf("com.github.i-am-cal:antisteal:1.2.0")`` under ``dependencies``.

It's running during the ``FMLClientSetupEvent``. If I'm doing something incorrectly, let me know.

**Comment by i-am-cal** [comment]
Hi! Antisteal doesn't require a modloader, so it must be implemented like a normal gradle library.

You would need to do the following for forge:

```gradle
repositories {
    ...
    maven { url 'https://jitpack.io' }
}
configurations {
    antisteal
}
dependencies {
    ...
    implementation fg.deobf(antisteal "com.github.i-am-cal:antisteal:1.1.0"))
}
jar {
    ...
    from {
        configurations.antisteal.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

Thanks, check back if this worked.

**Comment by AnonymousHacker1279** [comment]
I updated my ``build.gradle``, but unfortunately I'm still getting the same error: 
``java.lang.ClassNotFoundException: i.am.cal.antisteal.Antisteal$CloseEvent``.

Is the ``FMLClientSetupEvent`` the wrong place for me run the ``Antisteal.check()`` method? I wonder if that has anything to do with it. Although I've also tried it during the ``FMLCommonSetupEvent`` and it did the same thing.

**Comment by i-am-cal** [comment]
Its because Antisteal isn't being included in your jar. I had this exact same problem on early test versions.

What happens if you remove `implementation`?

**Comment by AnonymousHacker1279** [comment]
If I remove ``implementation`` it prevents the IDE from resolving it.

And if I check the MDK for their example ``build.gradle`` they would have it setup as ``implementation fg.deobf("com.github.i-am-cal:antisteal:1.2.0")``

**Comment by i-am-cal** [comment]
It says fg.deobf() is specifically for **mods**, since Antisteal isn't a mod fg.deobf wont work with antisteal.

**Comment by i-am-cal** [comment]
You could try use the shadow plugin instead of raw gradle jar-in-jar.

Checkout https://imperceptiblethoughts.com/shadow/getting-started/

**Comment by AnonymousHacker1279** [comment]
Ah, I didn't realize that ``fg.deobf`` was specifically for mods. I'll check out the shadow plugin. Although I don't think the main issue was that it wasn't being included in my built jar, as I couldn't use the ``runClient`` configuration to test it within my IDE because it would crash.

**Comment by i-am-cal** [comment]
You can simply check if it's being included by opening the jar as a archive using 7zip and seeing if AntiSteal is there.

**Comment by i-am-cal** [comment]
You might need to run checking on a later event. Such as `FMLClientSetupEvent`

**Comment by AnonymousHacker1279** [comment]
AntiSteal is being included in the final jar. And I am running it during the ``FMLClientSetupEvent``.

**Comment by i-am-cal** [comment]
Hmm, weird. I'm honestly clueless with forge stuff. Worst case scenario just copy the `i.am.cal.antisteal` package folder from github into your project.

**Comment by AnonymousHacker1279** [comment]
Yeah I'll try copying the package into my project. It seems like a Forge issue, so hopefully it gets fixed soon.

**Comment by i-am-cal** [comment]
# Temporary Workaround

Copy the i.am.cal.antisteal package into your project.
